server:
  port: 9009

duid-attributes:
  year: 2000
  month: 1
  day: 1
  hour: 00
  minute: 00
  maxNodeId: 1024
  initialBits: 41
  totalBits: 64
  nodeIdBits: 13
  randomIdBound: 1024

event-db:
  driver: "postgresql"
  host: "192.168.0.103"
  port: 5432
  user: "postgres"
  password: "password"
  database: "distributed_uid"
  poolSize: 5
  maxIdleTime: 1000



